
export const techs = [
    { id: 1, name: "React" },
    { id: 2, name: "Node.js" },
    { id: 3, name: "TypeScript" },
    { id: 4, name: "JavaScript" },
    { id: 5, name: "Python" },
    { id: 6, name: "Django" },
    { id: 7, name: "Flask" },
    { id: 8, name: "FastAPI" },
    { id: 9, name: "HTML" },
    { id: 10, name: "CSS" },
    { id: 11, name: "Tailwind CSS" },
    { id: 12, name: "Bootstrap" },
    { id: 13, name: "MySQL" },
    { id: 14, name: "PostgreSQL" },
    { id: 15, name: "MongoDB" },
    { id: 16, name: "Express.js" },
    { id: 17, name: "Next.js" },
    { id: 18, name: "Vue.js" },
    { id: 19, name: "Angular" },
    { id: 20, name: "Firebase" },
    { id: 21, name: "Docker" },
    { id: 22, name: "Kubernetes" },
    { id: 23, name: "AWS" },
    { id: 24, name: "Azure" },
    { id: 25, name: "GraphQL" },
    { id: 26, name: "Redux" },
    { id: 27, name: "SASS" },
    { id: 28, name: "React Native" },
    { id: 29, name: "Flutter" },
    { id: 30, name: "Jest" }
  ];
  